[package]
name = "catch-movie"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.29", features = ["derive"] }
reqwest = { version = "0.12.12", features = ["json"] }
scraper = "0.22.0"
tokio = { version = "1.43.0", features = ["full"] }
webbrowser = "1.0.3"
